package io.github.xxparthparekhxx.composekeyboard.input.swipe.nn

import org.junit.Assert.*
import org.junit.Test
import java.io.DataInputStream
import java.io.File
import java.io.FileInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.abs

/**
 * Numerical parity against torch: the exact silent-failure mode the decoder
 * warns about. A botched re-export (wrong BN folding, transposed weight) or a
 * transcription drift in conv1d/depthwise/emit ships with no crash — just
 * quietly worse predictions.
 *
 * Fixture `swipe_reference.bin` is generated by ml/tools/export_weights.py
 * from the same seed it dumps to runs/reference.npz, and must be refreshed on
 * every re-export. Layout of the file:
 *   magic 'SWRF', version i32=1, then 5 sections each [count i32][float32 LE]:
 *   xy torch order (1,2,64) -> [x0..x63, y0..y63],
 *   keys (1,26,2) -> [x0,y0,x1,y1,...],
 *   feats (1,8,64) channel-major,
 *   logp (1,32,27) row-major [t*27+k],
 *   gate (1,32).
 */
class SwipeNetParityTest {

    private data class Fixture(
        val xyTorch: FloatArray,
        val keys: FloatArray,
        val featsTorch: FloatArray,
        val logp: FloatArray,
        val gate: FloatArray
    )

    private fun loadFixture(): Fixture {
        val fromResources = javaClass.getResourceAsStream("/swipe_reference.bin")
        if (fromResources != null) {
            fromResources.use { return readFixture(it) }
        }
        // Fallback for IDEs that don't put test resources on the classpath:
        // read the checked-in file directly.
        val candidates = listOf(
            File("app/src/test/resources/swipe_reference.bin"),
            File("src/test/resources/swipe_reference.bin"),
            File("../app/src/test/resources/swipe_reference.bin")
        )
        val file = candidates.firstOrNull { it.exists() }
        assertNotNull("swipe_reference.bin not found (resources + $candidates)", file)
        FileInputStream(file!!).use { return readFixture(it) }
    }

    private fun readFixture(stream: java.io.InputStream): Fixture {
        val input = DataInputStream(stream.buffered(8192))
        val magic = ByteArray(4).also { input.readFully(it) }
        assertEquals("SWRF", String(magic))
        assertEquals(1, readLE(input))
        fun section(): FloatArray {
            val n = readLE(input)
            assertTrue("bad section size $n", n in 1..65536)
            val bytes = ByteArray(n * 4)
            input.readFully(bytes)
            val out = FloatArray(n)
            ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer().get(out)
            return out
        }
        return Fixture(section(), section(), section(), section(), section())
    }

    private fun readLE(input: DataInputStream): Int {
        val b = ByteArray(4).also { input.readFully(it) }
        return ByteBuffer.wrap(b).order(ByteOrder.LITTLE_ENDIAN).int
    }

    private fun loadEncoder(): SwipeNet {
        val candidates = listOf(
            File("src/main/assets/swipe_encoder.bin"),
            File("app/src/main/assets/swipe_encoder.bin"),
            File("../app/src/main/assets/swipe_encoder.bin")
        )
        val file = candidates.firstOrNull { it.exists() }
        assertNotNull("swipe_encoder.bin not found", file)
        return FileInputStream(file!!).use { SwipeNet.load(it) }
    }

    @Test
    fun forward_matchesTorchReference() {
        val net = loadEncoder()
        val ref = loadFixture()

        assertEquals(2 * SwipeNet.T_IN, ref.xyTorch.size)
        assertEquals(26 * 2, ref.keys.size)
        assertEquals(SwipeNet.T_OUT * (SwipeNet.ALPHABET + 1), ref.logp.size)
        assertEquals(SwipeNet.T_OUT, ref.gate.size)

        // Torch (2,64) channel-major -> Kotlin interleaved [x0,y0,...].
        val xy = FloatArray(SwipeNet.T_IN * 2)
        for (i in 0 until SwipeNet.T_IN) {
            xy[i * 2] = ref.xyTorch[i]
            xy[i * 2 + 1] = ref.xyTorch[SwipeNet.T_IN + i]
        }
        val keyX = FloatArray(26) { ref.keys[it * 2] }
        val keyY = FloatArray(26) { ref.keys[it * 2 + 1] }
        val basis = SwipeNet.basisFor(keyX, keyY)

        net.forward(xy, basis)

        // --- emissions (logp): the headline assertion; covers the whole trunk ---
        var maxErr = 0f
        var sumErr = 0.0
        for (i in ref.logp.indices) {
            val e = abs(net.emissions[i] - ref.logp[i])
            if (e > maxErr) maxErr = e
            sumErr += e
            assertFalse("emission NaN at $i", net.emissions[i].isNaN())
        }
        val meanErr = (sumErr / ref.logp.size).toFloat()
        println("parity: emissions maxErr=$maxErr meanErr=$meanErr")
        assertTrue("emissions drifted: maxErr=$maxErr (tolerance $EMISSION_TOL)", maxErr <= EMISSION_TOL)

        // --- gate head, via reflection (private scratch buffer) ---
        // Kotlin keeps raw gate *logits*; torch reference stores sigmoid(logits).
        val gateField = SwipeNet::class.java.getDeclaredField("gate").apply { isAccessible = true }
        val gateActual = gateField.get(net) as FloatArray
        var maxGateErr = 0f
        for (i in ref.gate.indices) {
            val prob = 1f / (1f + kotlin.math.exp(-gateActual[i]))
            val e = abs(prob - ref.gate[i])
            if (e > maxGateErr) maxGateErr = e
        }
        println("parity: gate maxErr=$maxGateErr")
        assertTrue("gate drifted: maxErr=$maxGateErr", maxGateErr <= GATE_TOL)

        // --- Savitzky-Golay features: torch channel-major -> Kotlin time-major ---
        val featField = SwipeNet::class.java.getDeclaredField("feat").apply { isAccessible = true }
        val featActual = featField.get(net) as FloatArray
        var maxFeatErr = 0f
        for (t in 0 until SwipeNet.T_IN) {
            for (c in 0 until 8) {
                val expected = ref.featsTorch[c * SwipeNet.T_IN + t]
                val e = abs(featActual[t * 8 + c] - expected)
                if (e > maxFeatErr) maxFeatErr = e
            }
        }
        println("parity: feats maxErr=$maxFeatErr")
        assertTrue("features drifted: maxErr=$maxFeatErr", maxFeatErr <= FEAT_TOL)
    }

    companion object {
        // JVM libm (cos/exp/log/atan2) is not bit-identical to torch/CPU; the
        // measured max errors on the reference seed are ~2e-6 (feats),
        // ~1e-5 (gate), ~5e-5 (emissions). Tolerances are set ~10-20x above
        // measurement: tight enough to catch a transposed weight or a flipped
        // BN fold, loose enough to survive a JDK update.
        private const val EMISSION_TOL = 1e-3f
        private const val GATE_TOL = 5e-4f
        private const val FEAT_TOL = 5e-4f
    }
}
